#!/usr/bin/env python3
"""Generate the neutral services-export fixtures for the business-report skill tests.

Run from this directory; xlwt is only needed for the legacy workbook:

    uv run --no-project --with xlwt --with openpyxl python make_example_services_export.py

The generator is deterministic: the same seed always produces the same rows, so
the CSV and XLS files can be regenerated byte for byte; the XLSX carries its zip
entry timestamps, so its bytes differ between runs while its cells do not.
Example Services Co. is an invented company; names, cities and amounts are made up.

Files written next to this script:

- example_services_export.csv   5,000 jobs, August 2025 to August 2026, plain numbers
- example_services_export.xlsx  the same rows on a "Jobs" sheet plus a "Notes" sheet
                                without a data table, so sheet selection is exercised
- example_services_export_small.csv  300 jobs, July and August 2026, amounts written
                                as "$1,234.50" under a "Total (USD)" header
- example_services_export_small.xls  the 300 rows as a legacy workbook
"""

from __future__ import annotations

import csv
import datetime as dt
import random
from pathlib import Path

HERE = Path(__file__).resolve().parent
SEED = 20260831

COLUMNS = ["Job #", "Completed On", "Customer Name", "Service Type", "Assigned To", "Invoice Status", "Source", "City", "Quantity", "Total"]

# (name, typical amount, share of jobs)
SERVICES = [
    ("Installation", 640.0, 0.22),
    ("Repair", 285.0, 0.36),
    ("Maintenance", 165.0, 0.24),
    ("Inspection", 95.0, 0.10),
    ("Consultation", 120.0, 0.06),
    ("Warranty", 0.0, 0.02),
]
TECHNICIANS = ["A. Rivera", "B. Chen", "C. Okafor", "D. Novak", "E. Schmidt", "F. Haddad"]
STATUSES = [("Paid", 0.82), ("Unpaid", 0.12), ("Cancelled", 0.06)]
SOURCES = [("Referral", 0.34), ("Website", 0.28), ("Repeat", 0.20), ("Phone", 0.12), ("Social", 0.06)]
CITIES = ["Springfield", "Riverside", "Fairview", "Greenville", "Franklin"]
CUSTOMER_WORDS = (
    ["Maple", "Harbor", "Oak", "Cedar", "Willow", "Summit", "River", "Lakeside", "Meadow", "Pine", "Hillcrest", "Bayview", "Elm", "Prairie", "Stone"],
    ["Street", "View", "Ridge", "Park", "Point", "Grove", "Creek", "Valley", "Heights", "Crossing"],
    ["Bakery", "Apartments", "Clinic", "Dental", "Market", "Studio", "Offices", "Homes", "Library", "School", "Cafe", "Garage", "Hotel", "Pharmacy", "Gym"],
)

# First day of each month covered by the large export and the relative number of
# jobs in it: a business growing through the year with a winter dip.
LARGE_MONTHS = [
    (dt.date(2025, 8, 1), 300),
    (dt.date(2025, 9, 1), 320),
    (dt.date(2025, 10, 1), 340),
    (dt.date(2025, 11, 1), 330),
    (dt.date(2025, 12, 1), 290),
    (dt.date(2026, 1, 1), 280),
    (dt.date(2026, 2, 1), 330),
    (dt.date(2026, 3, 1), 360),
    (dt.date(2026, 4, 1), 380),
    (dt.date(2026, 5, 1), 400),
    (dt.date(2026, 6, 1), 420),
    (dt.date(2026, 7, 1), 440),
    (dt.date(2026, 8, 1), 460),
]
SMALL_MONTHS = [(dt.date(2026, 7, 1), 130), (dt.date(2026, 8, 1), 170)]


def _days_in_month(first: dt.date) -> int:
    following = (first.replace(day=28) + dt.timedelta(days=4)).replace(day=1)
    return (following - first).days


def _weighted(rng: random.Random, options: list[tuple[str, float]]) -> str:
    return rng.choices([name for name, _ in options], weights=[weight for _, weight in options])[0]


def _customers(rng: random.Random, count: int) -> list[str]:
    names: list[str] = []
    seen: set[str] = set()
    while len(names) < count:
        name = " ".join(rng.choice(words) for words in CUSTOMER_WORDS)
        if name not in seen:
            seen.add(name)
            names.append(name)
    return names


def generate_rows(count: int, months: list[tuple[dt.date, int]], seed: int) -> list[list[object]]:
    """Return ``count`` job rows sorted by date, ids assigned in that order."""

    rng = random.Random(seed)
    customers = _customers(rng, max(40, count // 12))
    rows: list[list[object]] = []
    for _ in range(count):
        month_index = rng.choices(range(len(months)), weights=[weight for _, weight in months])[0]
        first = months[month_index][0]
        date = first + dt.timedelta(days=rng.randrange(_days_in_month(first)))
        # The customer base grows through the year: half of the names exist from
        # the first month, the rest arrive month by month, so every later month
        # has both new and returning customers.
        pool = customers[: max(20, len(customers) * (len(months) + month_index) // (2 * len(months)))]
        service, typical, _share = rng.choices(SERVICES, weights=[share for _, _, share in SERVICES])[0]
        status = _weighted(rng, STATUSES)
        quantity = rng.choices([1, 2, 3, 4], weights=[70, 18, 8, 4])[0]
        if typical == 0.0 or status == "Cancelled":
            total = 0.0
        else:
            total = round(typical * quantity * rng.uniform(0.7, 1.4), 2)
        technician = "" if rng.random() < 0.006 else rng.choice(TECHNICIANS)
        # Returning customers are more likely than brand-new ones.
        customer = rng.choice(pool[: max(20, len(pool) * 2 // 3)]) if rng.random() < 0.75 else rng.choice(pool)
        rows.append([None, date, customer, service, technician, status, _weighted(rng, SOURCES), rng.choice(CITIES), quantity, total])
    rows.sort(key=lambda row: (row[1], row[2]))
    for index, row in enumerate(rows):
        row[0] = f"J-{10001 + index}"
    return rows


def write_csv(path: Path, rows: list[list[object]], *, currency_strings: bool) -> None:
    columns = list(COLUMNS)
    if currency_strings:
        columns[-1] = "Total (USD)"
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(columns)
        for row in rows:
            out = list(row)
            out[1] = row[1].isoformat()
            out[-1] = f"${row[-1]:,.2f}" if currency_strings else f"{row[-1]:.2f}"
            writer.writerow(out)


def write_xlsx(path: Path, rows: list[list[object]]) -> None:
    import openpyxl

    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = "Jobs"
    sheet.append(COLUMNS)
    for row in rows:
        sheet.append(row)
    for cell in sheet["B"][1:]:
        cell.number_format = "yyyy-mm-dd"
    notes = workbook.create_sheet("Notes")
    notes["A1"] = "Exported 2026-09-01 from the scheduling system"
    notes["A2"] = "Amounts in USD"
    # Fixed document timestamps keep the file byte-for-byte reproducible.
    workbook.properties.created = dt.datetime(2026, 9, 1, 8, 0, 0)
    workbook.properties.modified = dt.datetime(2026, 9, 1, 8, 0, 0)
    workbook.save(path)


def write_xls(path: Path, rows: list[list[object]]) -> None:
    import xlwt

    workbook = xlwt.Workbook()
    sheet = workbook.add_sheet("Jobs")
    date_style = xlwt.XFStyle()
    date_style.num_format_str = "yyyy-mm-dd"
    for column, name in enumerate(COLUMNS):
        sheet.write(0, column, name)
    for row_index, row in enumerate(rows, start=1):
        for column, value in enumerate(row):
            if column == 1:
                sheet.write(row_index, column, value, date_style)
            else:
                sheet.write(row_index, column, value)
    workbook.save(str(path))


def main() -> None:
    large = generate_rows(5000, LARGE_MONTHS, SEED)
    small = generate_rows(300, SMALL_MONTHS, SEED + 1)
    write_csv(HERE / "example_services_export.csv", large, currency_strings=False)
    write_xlsx(HERE / "example_services_export.xlsx", large)
    write_csv(HERE / "example_services_export_small.csv", small, currency_strings=True)
    write_xls(HERE / "example_services_export_small.xls", small)
    for label, rows in (("large", large), ("small", small)):
        by_month: dict[str, int] = {}
        for row in rows:
            key = row[1].strftime("%Y-%m")
            by_month[key] = by_month.get(key, 0) + 1
        print(label, by_month)


if __name__ == "__main__":
    main()
