"""Public contracts for DeerFlow extensions.

This package MUST NOT import `deerflow`. Every host contract an extension
needs lives here, while framework imports remain direct extension dependencies;
extensions can therefore be released independently of the host.
"""

from __future__ import annotations

from deerflow_extension_api.assembly import (
    AgentAssemblyDescriptor,
    AgentAssemblyObserver,
    MiddlewareDescriptor,
    ToolDescriptor,
)
from deerflow_extension_api.auth import (
    EXTENSION_PRINCIPAL_RESOLVER_KEY,
    ExtensionPrincipal,
    require_admin,
    resolve_principal,
)
from deerflow_extension_api.authorization import (
    AUTHORIZATION_PROVIDER_CAPABILITY_API_VERSION,
    AUTHORIZATION_PROVIDER_KIND,
    AuthorizationProvider,
    AuthorizationProviderFactory,
    AuthzDecision,
    AuthzReason,
    AuthzRequest,
    Principal,
)
from deerflow_extension_api.compaction import (
    CompactionEvent,
    ContextCompactionObserver,
)
from deerflow_extension_api.constraints import (
    INVOCATION_CONSTRAINTS_CAPABILITY_API_VERSION,
    INVOCATION_CONSTRAINTS_CAPABILITY_API_VERSION_V2,
    INVOCATION_CONSTRAINTS_KIND,
    INVOCATION_CONSTRAINTS_REQUIRED_CAPABILITY,
    INVOCATION_CONSTRAINTS_REQUIRED_CAPABILITY_V2,
    INVOCATION_CONSTRAINTS_V2_SUPPORTED_OBLIGATIONS,
    ConstraintIndeterminate,
    ConstraintProjectionRequestV1,
    ConstraintProjectionRequestV2,
    ConstraintProjectionV1,
    ConstraintProjectionV2,
    ConstraintRejected,
    InvocationConstraintsProvider,
    InvocationConstraintsProviderFactory,
    InvocationConstraintsProviderV2,
)
from deerflow_extension_api.contracts import (
    ExtensionInstall,
    ExtensionRegistry,
    ExtensionRuntimeDeps,
    ExtensionService,
    HostPolicySnapshot,
    MiddlewareContributor,
    ReplicaSafety,
    SystemModelCallObserver,
    SystemModelRequest,
    SystemModelResult,
    SystemOperationKind,
    TaskInfo,
    TaskLifecycleContributor,
    TaskOutcome,
    extension,
)
from deerflow_extension_api.contributors import (
    ORIGIN_CONTRIBUTOR_CAPABILITY_API_VERSION,
    ORIGIN_CONTRIBUTOR_KIND,
    RUN_CONTEXT_CONTRIBUTOR_CAPABILITY_API_VERSION,
    RUN_CONTEXT_CONTRIBUTOR_KIND,
    NamespacedContextReferenceV1,
    OriginContributionRequestV1,
    OriginContributionV1,
    OriginContributor,
    OriginContributorFactory,
    PrincipalProjectionV1,
    ResolvedAgentRevisionReferenceV1,
    ResolvedProfileRevisionReferenceV1,
    RunContextContributionRequestV1,
    RunContextContributionV1,
    RunContextContributor,
    RunContextContributorFactory,
    SafeContextReferenceV1,
    SealedOriginV1,
    TrustedRunContextV1,
)
from deerflow_extension_api.credentials import (
    AUTHORITY_ALIASES_V1,
    AUTHORITY_CANONICALIZATION_VERSION,
    AuthenticationMethod,
    CredentialEvidenceV1,
    VerifiedActorContextV1,
    authority_categories_v1,
    canonicalize_authority_v1,
    effective_authority_digest_v1,
)
from deerflow_extension_api.health import (
    CapabilityHealthProbe,
    CapabilityHealthResult,
    CapabilityHealthStatus,
)
from deerflow_extension_api.identifiers import (
    AGENT_IDENTIFIER_PATTERN,
    MCP_SERVER_IDENTIFIER_MAX_BYTES,
    MCP_TOOL_IDENTIFIER_PATTERN,
    MODEL_PROFILE_IDENTIFIER_MAX_BYTES,
    RESERVED_AGENT_IDENTIFIERS,
    THREAD_IDENTIFIER_PATTERN,
    canonicalize_agent_identifier,
    validate_agent_identifier,
    validate_mcp_server_identifier,
    validate_mcp_tool_identifier,
    validate_model_profile_identifier,
    validate_thread_identifier,
)
from deerflow_extension_api.identity import (
    ActingServiceV1,
    EffectiveSubjectV1,
    InvocationIdentityV1,
)
from deerflow_extension_api.mcp import (
    MCP_INTERCEPTOR_CAPABILITY_API_VERSION,
    MCP_INTERCEPTOR_KIND,
    McpCallIndeterminateV1,
    McpCallProjectionV1,
    McpCallRejectedV1,
    McpHeaderV1,
    McpInterceptor,
    McpInterceptorDescriptor,
    PreparedMcpCallV1,
)
from deerflow_extension_api.placement import (
    AgentBuildContext,
    AgentScope,
    MiddlewarePlacement,
    Placement,
)
from deerflow_extension_api.provenance import (
    MESSAGE_CONTENT_KIND_KEY,
    MESSAGE_PRODUCER_ENTITY_ID_KEY,
    MESSAGE_PRODUCER_KIND_KEY,
    PROVENANCE_KEYS,
    ContentKind,
    MessageProvenance,
    provenance_kwargs,
    read_provenance,
)
from deerflow_extension_api.release import (
    ReleasePolicyProvider,
    canonical_hash,
    canonical_json,
    collect_release_policies,
)
from deerflow_extension_api.runtime_bridge import (
    EXTENSION_TASK_STORE_KEY,
    task_store_from_runtime,
)
from deerflow_extension_api.state import ExtensionData
from deerflow_extension_api.tenant import TenantReferenceV1

#: Contract version. Pre-1.0 minors may break and only patches promise to be
#: additive. From 1.0 on, bump the major on any breaking change; see the spec's
#: evolution rules for what counts as additive.
API_VERSION = "0.13.1"

__all__ = [
    "API_VERSION",
    "AGENT_IDENTIFIER_PATTERN",
    "MCP_SERVER_IDENTIFIER_MAX_BYTES",
    "MCP_TOOL_IDENTIFIER_PATTERN",
    "MODEL_PROFILE_IDENTIFIER_MAX_BYTES",
    "RESERVED_AGENT_IDENTIFIERS",
    "THREAD_IDENTIFIER_PATTERN",
    "AUTHORIZATION_PROVIDER_CAPABILITY_API_VERSION",
    "AUTHORIZATION_PROVIDER_KIND",
    "AUTHORITY_ALIASES_V1",
    "AUTHORITY_CANONICALIZATION_VERSION",
    "INVOCATION_CONSTRAINTS_CAPABILITY_API_VERSION",
    "INVOCATION_CONSTRAINTS_CAPABILITY_API_VERSION_V2",
    "INVOCATION_CONSTRAINTS_KIND",
    "INVOCATION_CONSTRAINTS_REQUIRED_CAPABILITY",
    "INVOCATION_CONSTRAINTS_REQUIRED_CAPABILITY_V2",
    "INVOCATION_CONSTRAINTS_V2_SUPPORTED_OBLIGATIONS",
    "MCP_INTERCEPTOR_CAPABILITY_API_VERSION",
    "MCP_INTERCEPTOR_KIND",
    "EXTENSION_PRINCIPAL_RESOLVER_KEY",
    "EXTENSION_TASK_STORE_KEY",
    "MESSAGE_CONTENT_KIND_KEY",
    "MESSAGE_PRODUCER_ENTITY_ID_KEY",
    "MESSAGE_PRODUCER_KIND_KEY",
    "PROVENANCE_KEYS",
    "AgentAssemblyDescriptor",
    "AgentAssemblyObserver",
    "AgentBuildContext",
    "AgentScope",
    "ActingServiceV1",
    "AuthenticationMethod",
    "AuthorizationProvider",
    "AuthorizationProviderFactory",
    "AuthzDecision",
    "AuthzReason",
    "AuthzRequest",
    "CapabilityHealthProbe",
    "CapabilityHealthResult",
    "CapabilityHealthStatus",
    "ConstraintIndeterminate",
    "ConstraintProjectionRequestV1",
    "ConstraintProjectionRequestV2",
    "ConstraintProjectionV1",
    "ConstraintProjectionV2",
    "ConstraintRejected",
    "CredentialEvidenceV1",
    "CompactionEvent",
    "ContentKind",
    "ContextCompactionObserver",
    "ExtensionData",
    "ExtensionInstall",
    "ExtensionPrincipal",
    "ExtensionRegistry",
    "EffectiveSubjectV1",
    "ExtensionRuntimeDeps",
    "ExtensionService",
    "HostPolicySnapshot",
    "InvocationConstraintsProvider",
    "InvocationConstraintsProviderFactory",
    "InvocationConstraintsProviderV2",
    "InvocationIdentityV1",
    "MessageProvenance",
    "MiddlewareContributor",
    "MiddlewareDescriptor",
    "MiddlewarePlacement",
    "Placement",
    "Principal",
    "ReplicaSafety",
    "McpCallIndeterminateV1",
    "McpCallProjectionV1",
    "McpCallRejectedV1",
    "McpHeaderV1",
    "McpInterceptor",
    "McpInterceptorDescriptor",
    "PreparedMcpCallV1",
    "ORIGIN_CONTRIBUTOR_CAPABILITY_API_VERSION",
    "ORIGIN_CONTRIBUTOR_KIND",
    "RUN_CONTEXT_CONTRIBUTOR_CAPABILITY_API_VERSION",
    "RUN_CONTEXT_CONTRIBUTOR_KIND",
    "OriginContributionRequestV1",
    "OriginContributionV1",
    "OriginContributor",
    "OriginContributorFactory",
    "NamespacedContextReferenceV1",
    "PrincipalProjectionV1",
    "ResolvedAgentRevisionReferenceV1",
    "ResolvedProfileRevisionReferenceV1",
    "RunContextContributionRequestV1",
    "RunContextContributionV1",
    "RunContextContributor",
    "RunContextContributorFactory",
    "SafeContextReferenceV1",
    "SealedOriginV1",
    "TrustedRunContextV1",
    "VerifiedActorContextV1",
    "ReleasePolicyProvider",
    "SystemModelCallObserver",
    "SystemModelRequest",
    "SystemModelResult",
    "SystemOperationKind",
    "TaskInfo",
    "TaskLifecycleContributor",
    "TaskOutcome",
    "TenantReferenceV1",
    "ToolDescriptor",
    "canonical_hash",
    "canonical_json",
    "authority_categories_v1",
    "canonicalize_authority_v1",
    "collect_release_policies",
    "extension",
    "provenance_kwargs",
    "read_provenance",
    "require_admin",
    "resolve_principal",
    "task_store_from_runtime",
    "canonicalize_agent_identifier",
    "validate_agent_identifier",
    "validate_mcp_server_identifier",
    "validate_mcp_tool_identifier",
    "validate_model_profile_identifier",
    "validate_thread_identifier",
    "effective_authority_digest_v1",
]
